### ISSUE TITLE
Support l10n en/fr

### ISSUE THREAD

**Issue by camelaissani** [camelaissani/loca#11]

**Comment by DawidvanGraan** [comment]
:+1: Would be nice as my French is not that good :smile:

**Comment by camelaissani** [comment]
Okay I start to work on it.

**Comment by camelaissani** [comment]
Still on it :) More than 40 files modified so far.
After few investigations, I am using [i18next](http://i18next.com/) framework for its ability to make translation on the front-end as well as on the back-end.

**Comment by DawidvanGraan** [comment]
Awesome! Wil keep an eye out for any changes!

**Comment by camelaissani** [comment]
No more French words in the code!
I translated almost everything except the template documents: lease contracts, invoices, rent notices...
I think we should do more than localization, we should adapt these documents to the legal rules of each countries.
See issue #12

**Comment by DawidvanGraan** [comment]
Excellent, well done! Great idea on the docs per country, really ads value to the site!

**Comment by camelaissani** [comment]
I found some omissions with date and on dashboard view
