### ISSUE TITLE
demo login isn't working

### ISSUE THREAD

**Issue by etewiah** [camelaissani/loca#16]
Looks like a great project but when I visit this url on your demo I get a message saying "demo.nuageprive.fr redirected you too many times" : 
https://demo.nuageprive.fr/login

Also, do you have credentials for the demo app to allow me to have a look?

Thanks

**Comment by camelaissani** [comment]
Okay I've fixed the demo website. The demo app is testable without any credentials.
Let me know your feedback.
Thanks

**Comment by etewiah** [comment]
Great, thanks!

I've just had a look now and it looks really slick.  Its fast and works well.  It takes a while to understand the functionality but it looks like it does quite a lot.  

I got interested because I'm working on a project to help estate agents create websites and one of the features I would like to add is the ability for them to manage their rental properties.  I will have a closer look later on to see if I can learn something from your code ;)

In the meantime if you're interested in my project you can have a look at it here:

https://github.com/etewiah/property_web_builder

**Comment by camelaissani** [comment]
I've seen your project as well. Actually they are complementary. Yours for buying and renting properties and mine for managing rentals ;-)

Loca has been a project on which I've experimented JavaScript. So the code and the architecture are far to be perfect. 

I will fix the accumulated technical debts as soon as possible. 
Also, I will change the UI and simplify some worklows to make it easier to use.

However the most important is to be able to extend Loca for customizing rental logics (contracts, computation of rent and expense, management of documents...) and make it compliant with the laws of different countries.
Thus Loca would be as a base platform for Real-estate management.

**Comment by etewiah** [comment]
Yes indeed, they are complementary and I think we could learn from each other ;)

It is a shame that there are so few open source projects in the real estate sector.  People pay a lot of money for real estate websites even though about 80% of the functionality in these sites is the same.  I really think there is a need for people to work together to create a base platform on which  other solutions can be built.

I think what would be really nice would be to have a standard API backend against which anyone could create a frontend in javascript (or a native mobile client)

I'm not there yet with PropertyWebBuilder but I'm working on it.  I'll keep you updated.

**Comment by camelaissani** [comment]
As the demo web site is working, can we close this issue?

**Comment by etewiah** [comment]
Ah, yes of course ;)
