### ISSUE TITLE
Proposal to write content/web copy for your About Us Page.

### ISSUE THREAD

**Issue by order4adwriter** [camelaissani/loca#21]
Hello @camelaissani ,

I've seen the demo for your real estate app Loca...and I must say that it looks pretty cool!

I am a professional copywriter and I 'd like to contribute to your repository by writing an About Loca / About Us  page content, privacy policy, Help/FAQ, Terms Of Use etc  and other necessary content  for your app.

My question is .... would you merge it into your repository when it is done? please let me know so I can get started as soon as possible.

Thanks.

**Comment by camelaissani** [comment]
Hello @order4adwriter,

I appreciate any help on this open source app :smile: 
Please contribute, I'll review and merge your work.

Thanks

**Comment by order4adwriter** [comment]
i  can be reached on discord order4adwriter #2544

**Comment by order4adwriter** [comment]
thanks for your  reply...getting to it now

**Comment by order4adwriter** [comment]
Hi @camelaissani ,

just sent you a pull request.
please confirm, review and merge .

thanks.

**Comment by order4adwriter** [comment]
hi @camelaissani ,

Still waiting for you to approve my pull request...

**Comment by order4adwriter** [comment]
Hello, are you there?

**Comment by camelaissani** [comment]
Yep, just focused on other topics.
Please be patient for my review, I'm not full time on my open source projects (unfortunately).

**Comment by order4adwriter** [comment]
Hi @camelaissani ,

I have just finished writing content for your about us page.

Look, I understand how busy you might be with work and all...but I really love contributing to your repository.
However, I must let you understand that I am a lot motivated  when I see my work being merged...not just because it shows that i did good but the fact that I also use it as a work sample to show to my paying clients. 
All I ask is that if you don't feel like merging it with the master repository, simply copy the text contents into a file and save it inside the master repository. that way, I believe you could always remove it later on if you feel the need to, without any serious issues.

At least let me have something to show clients as proof of my copywriting ability.

I'd appreciate it so much if you could understand me a little and help me out a little as well.

**Comment by camelaissani** [comment]
Please see my comments in #22

**Comment by order4adwriter** [comment]
hello @camelaissani ,

Still haven't gotten your reply to my recent edits to both page contents as pr your requests.

 I get you are probably very busy and this project is like a side gig for you... but C'mon man, you are really not helping  or encouraging me right now with your silence.

 If they are ok by you, could you please merge them to the master repo....

thanks.

**Comment by order4adwriter** [comment]
oh and by the way, I've already started work on contents for the readme.me file as per your requests.

Hope you can now understand why it seems I am bugging you, but I really am not... just eager to get on with the writing tasks  and  I am encouraged to do more when you reply my messages or show some interest in my work, and merge my finished work,as quickly as possible.

**Comment by camelaissani** [comment]
Hi @order4adwriter ,
Thanks for your patience.
Could you report your work in these two files please:
- [ABOUT.md](https://github.com/camelaissani/loca/blob/master/documentation/ABOUT.md)
- [README.md](https://github.com/camelaissani/loca/blob/master/documentation/README.md)

**Comment by order4adwriter** [comment]
Hi ,

I just saw your message in my email right now... Please give me a little
time....will do so tomorrow...

Thanks

On Apr 1, 2018 11:15 AM, "Camel Aissani" <notifications@github.com> wrote:

Hi @order4adwriter <https://github.com/order4adwriter> ,
Thanks for your patience.
Could you report your work in these two files please:

   - ABOUT.md
   <https://github.com/camelaissani/loca/blob/master/documentation/ABOUT.md>
   - README.md
   <https://github.com/camelaissani/loca/blob/master/documentation/README.md>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/camelaissani/loca/issues/21#issuecomment-377776750>,
or mute
the thread

**Comment by camelaissani** [comment]
Okay fine

**Comment by order4adwriter** [comment]
Ok, updates made...please set up a .md file for the homepage as well...if you haven't already.

also, please merge them all asap.

Thanks again.

**Comment by camelaissani** [comment]
Should we close this issue as your PRs were merged?

**Comment by camelaissani** [comment]
All PRs have been merged. 
Thanks for your time and your contribution.

**Comment by order4adwriter** [comment]
Hi @camelaissani,

I also want to write copy foor your FAQs page and also for  a Terms Of Servicepage as well....

Is this ok...and do you have any specific information or question you'd like answered in a particular way?

Better yet, can I at least write them first for you to peruse and review to your preferences... just like the previous ones?

Either way, please let me know asap.

Thanks again for allowing me contribute in my own little way to the future success of your open source app.

**Comment by camelaissani** [comment]
Hi @order4adwriter,
I apologize for my very late answer...
Please feel free to propose any documents if you think they're relevant for this open source project.
Thx

**Comment by order4adwriter** [comment]
ok....

thanks for the reply.... the way I see it, its better late than never....

Anyway , I will be writing an FAQ page content for the loca site... for you to go through and merge if you are satisfied with it ...will send in the pull request over very soon.

Thanks

**Comment by camelaissani** [comment]
@order4adwriter I'll close this issue. Feel free to open another one for other contributions.
