### ISSUE TITLE
How to translate

### ISSUE THREAD

**Issue by drique** [camelaissani/loca#27]
Hello, I've created an pt.json file with translated strings and placed it on locales folder.
How to make the website to use the created json?
For testing purposes I've tried renaming pt.json as en.json, but even with this, few strings are translated on the website.

**Comment by camelaissani** [comment]
Hello,
Normally, you just have to put the `pt.json` file in the [locales](https://github.com/camelaissani/loca/tree/master/frontend/locales) directory, and change the default language of the browser to Portuguese.

I would say after you will have to update the Loca container. Here it is the procedure:

Stop the application:
```bash
./mre stop
```
Build the container from the `loca` directory:
```bash
docker build .
```

And relaunch the app:
```bash
./mre start
```

Don't forget to change the browser language :wink:

**Comment by camelaissani** [comment]
I forgot to mention that English is the fallback language.
Then if you've forgotten to translate some words in Portuguese, the English version will be displayed in the application for those ones.

**Comment by drique** [comment]
It worked after running:
`docker commit containerid mre/loca`

**Comment by drique** [comment]
But there's a major bug.
When using any non-english language you can't click on any button
Tested with fr and pt
Please test yourself and reply

**Comment by drique** [comment]
Working ok after adding the language but with en on the top of the list. Everything translated. Closing issue. Thanks

**Comment by drique** [comment]
I think it's ok to ask here, it's related to translation.
Is there any implemented way to modify currency?

**Comment by drique** [comment]
I've already modified pt.json
```
    "__fmt_date__": "DD-MM-YYYY",
    "__fmt_datetime__": "DD-MM-YYYY HH[h]M",
```
the problem is in tenants page, where loca specifically asks for MM-DD-YYYY.
I'll take a look at all this as soon as I can

**Comment by drique** [comment]
"But there's a major bug.
When using any non-english language you can't click on any button
Tested with fr and pt
Please test yourself and reply"

Built everything again and this still occurs.
Maybe I was able to fix this the other time modifying the code, like changing fallback to pt etc, without doing nothing it still doesn't work

**Comment by camelaissani** [comment]
I just created those issues #32 and #33 for hard coded currency and phone number format.

**Comment by camelaissani** [comment]
My last fix should make the buttons work again and fix the issue with the date format on the tenant form.

**Comment by drique** [comment]
I'll test. A question: I live in brazil, should the json file be pt-br.json?

**Comment by camelaissani** [comment]
Yes but I've to test first if it works correctly.
You can keep using `pt.json` for now.

**Comment by camelaissani** [comment]
@drique sorry but same kind of task should be done again there https://github.com/microrealestate/microrealestate

**Comment by camelaissani** [comment]
Here is the issue created in the new repository https://github.com/microrealestate/microrealestate/issues/18
