### ISSUE TITLE
Disable demo mode

### ISSUE THREAD

**Issue by drique** [camelaissani/loca#28]
Hello,
How to disable demo mode and allow login, signup and mailing?

**Comment by camelaissani** [comment]
Hello,

Ensure the application has stopped:

```bash
./mre stop
```
After, you can disable the demo mode and allow login, signup by changing few lines in [prod.env file](https://github.com/microrealestate/microrealestate/blob/master/prod.env).
 
For the signup just set to true the `PRODUCTIVE` variable:
```bash
PRODUCTIVE=true
```

For the login and to disable the demo mode, set the variable `DEMO_MODE` to false:
```bash
DEMO_MODE=false
```

For the emails, you first have to create an account on [mailgun](https://www.mailgun.com/) (you can send 10,000 emails free every month).
Currently, this is the only email engine implemented in Loca.

After you just have to update the [prod.env file](https://github.com/microrealestate/microrealestate/blob/master/prod.env).

```bash
MAILGUN_API_KEY=your_api_key
MAILGUN_DOMAIN=mg.example.com
EMAIL_FROM="Example <noreply@example.com>"
EMAIL_REPLY_TO=customer-service@example.com
EMAIL_BCC=manager1@example.com,manager2@example.com
```

`MAILGUN` variables come from mailgun account.

`EMAIL` variables are the ones you want to use when mailgun will send emails.

**Comment by drique** [comment]
Thanks. It worked! Closing this issue. Please take a look at #27
