### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dee-y** [camelaissani/loca#30]
Hi there, i am a graphic designer and would love to contribute a logo to your project because it's opensource. If you don't already have a logo, please let me know. 

Best regards,
Dee.

**Comment by camelaissani** [comment]
Hi @dee-y, thanks again for your contribution request.
You can make a PR on this repository which is a sub module of [microrealestate](https://github.com/microrealestate/microrealestate).

Here is the link of the issue you've opened on this repository https://github.com/microrealestate/microrealestate/issues/1

**Comment by dee-y** [comment]
Oh i see, didn't know you guys were affiliated. Closing this issue now. Thank you.

**Comment by camelaissani** [comment]
I reopened this issue.
Could you do your future PR on this repository rather than on microrealestate.
I'll close the issue there.

**Comment by camelaissani** [comment]
You can glance at this [page](https://github.com/camelaissani/loca/tree/master/documentation) to figure out what this application is about.

**Comment by dee-y** [comment]
Owk...duly noted
