### ISSUE TITLE
Currency is hard-coded

### ISSUE THREAD

**Issue by camelaissani** [camelaissani/loca#32]
The currency displayed in the application is Euro. 
As this is hard-coded the application cannot be usable with other currencies.

**Comment by camelaissani** [comment]
@drique could you check that the fix work on your side please?

**Comment by drique** [comment]
It works. Theres a minor difference on currency format, in Brazil currency symbol is displayed before values, but I don't think it's worth fixing it at the moment =p or ever xD

**Comment by camelaissani** [comment]
The fix breaks the French version... I'm gonna rework this.
Please keep this issue open.

**Comment by camelaissani** [comment]
Now it should work properly for any languages.

**Comment by camelaissani** [comment]
@drique Should I close this issue?

**Comment by camelaissani** [comment]
I'll close the issue. Next developments will be done there https://github.com/microrealestate/microrealestate
