### ISSUE TITLE
Local taxes and specific costs

### ISSUE THREAD

**Issue by drique** [camelaissani/loca#34]
There should be an option to allow the software to make available specific taxes. Maybe selecting country.
As I can't do this, for while I'll just code over.
But with the mentioned improvement there would be available options available to the user.
In my case there is a need to fill and show costs of water, electricity, condominium fees, etc

**Comment by camelaissani** [comment]
Those taxes should be added by property?

**Comment by drique** [comment]
Probably it would be best to have select boxes on the registration of each property, because sometimes these taxes are already included in rent price

**Comment by camelaissani** [comment]
Is this https://github.com/microrealestate/microrealestate/blob/master/picture/tenantcontract.png enough to fix the issue?
