### ISSUE TITLE
How can I customize the lease template?

### ISSUE THREAD

**Issue by pancodia** [camelaissani/loca#45]
This project seems very helpful for me to manage my tenets in my house. However, I have my own customized lease template. How can I create lease based on my own template?

**Comment by camelaissani** [comment]
Currently the lease template is in french... I haven't find the time so for to make it more generic.
Actually, all the templates are here: https://github.com/camelaissani/loca/tree/master/backend/pages/print/view

You might adapt the contract by modifiying this page https://github.com/camelaissani/loca/blob/master/backend/pages/print/view/contract.ejs
and eventually change the document header and footer: 
- https://github.com/camelaissani/loca/blob/master/backend/pages/print/view/partials/header.ejs
- https://github.com/camelaissani/loca/blob/master/backend/pages/print/view/partials/footer.ejs

It's not convenient but I think about make that more customizable by relying on markdown templates.

**Comment by pancodia** [comment]
Thank you for pointing me to the right direction. I think this is a good start for adapting the project for my usecase. 
Yeah, I think markdown templates would be more generic and easier to customize.

**Comment by camelaissani** [comment]
I'm working on a solution.

**Comment by camelaissani** [comment]
This is currently addressed in https://github.com/microrealestate/microrealestate/issues/14
