### ISSUE TITLE
Working state

### ISSUE THREAD

**Issue by nrgapple** [camelaissani/loca#46]
Is this project in a working state?

If not, I would willing to help with missing parts

**Comment by camelaissani** [comment]
Any help is welcome. Feel free to contribute.

**Comment by nrgapple** [comment]
I'm trying to understand the structure:

Is loca the frontend or or is `frontend` the frontend?

Which is facing the tenants and which is for the manager? 

Is `frontend` stil incomplete?

**Comment by camelaissani** [comment]
`loca` is the frontend and the backend. In the next version, I'd like to remove the UI code from it and keep only with the backend code in the `loca` repository. Then at some point the `frontend` will be the UI of the application.
The UI will be written in React and currently I'm evaluating NextJS.

**Comment by camelaissani** [comment]
Please refer this repository for next developments https://github.com/microrealestate/microrealestate
